//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 31.03.2026
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	void jedz();
	void spij();
private:
	int wiek;
	double waga;
};

#endif  //_SSAK_H
